# Generated by Django 5.0.6 on 2024-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='soluong',
            field=models.IntegerField(default=0),
        ),
    ]
